<a href="https://colab.research.google.com/github/spike-commander/Iris-Classification-Machine-Learning-Model/blob/main/iris-classification-machine-learning-model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Second Machine Learning Model (Iris Detection)

## Library Imports (Numpy, Pandas)

In [ ]:
import pandas as pd
import numpy as np

## Data Prepration

**Species Convertion: setosa -> 1, virgininca -> 2, versicolor -> 3**

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/iris.csv')
species_map = {
    'setosa': 1,
    'virginica': 2,
    'versicolor': 3
}
data['Species'] = data['Species'].map(species_map)
data

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

## Data Sepration (into X and Y )

In [ ]:
y = data['Species']

x = data.drop('Species', axis = 1)

In [ ]:
from sklearn.model_selection import train_test_split

x_test, x_train, y_test, y_train = train_test_split(x, y, test_size = 0.2, random_state = 100)

y_train

128    2
11     1
118    2
15     1
123    2
135    2
32     1
1      1
116    2
45     1
40     1
115    2
26     1
28     1
145    2
97     3
62     3
77     3
122    2
112    2
125    2
31     1
146    2
29     1
69     3
149    2
75     3
20     1
73     3
120    2
Name: Species, dtype: int64

## Model Building

**Should not use the Linear Regression Model, It's just predicts contiunes numbers only, dosen't classifies**

## Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

LinearRegression()

### Applying Model to make Prediction

In [ ]:
y_lr_train_pred = lr.predict(x_train).astype(int)
y_lr_test_pred = lr.predict(x_test).astype(int)

y_lr_train_pred

array([2, 1, 2, 0, 2, 2, 0, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1,
       2, 1, 2, 2, 1, 1, 2, 1])

## Evaluate Model Performance (Linear REgression)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

lr_train_mse = mean_squared_error(y_train, y_lr_train_pred)
lr_train_r2 = r2_score(y_train, y_lr_train_pred)

lr_test_mse = mean_squared_error(y_test, y_lr_test_pred)
lr_test_r2 = r2_score(y_test, y_lr_test_pred)

print("lr_train_mse = ", lr_train_mse)
print("lr_train_r2 = ", lr_train_r2)
print("---------------------------------------")
print("lr_test_mse = ", lr_test_mse)
print("lr_test_r2 = ", lr_test_r2)

lr_train_mse =  0.4666666666666667
lr_train_r2 =  0.1340206185567011
---------------------------------------
lr_test_mse =  0.775
lr_test_r2 =  -0.12330145948666327

## Classification Model

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report

svm = SVC(kernel='linear', random_state=42)
svm.fit(x_train, y_train)
svm

SVC(kernel='linear', random_state=42)

### Applying Model To make Prediction

In [ ]:
svm_pred = svm.predict(x_test)
svm_pred

array([3, 3, 2, 1, 1, 3, 1, 3, 2, 2, 1, 3, 2, 2, 1, 1, 1, 1, 3, 1, 1, 1,
       3, 2, 2, 3, 2, 3, 2, 2, 3, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 3, 2, 2,
       2, 1, 3, 2, 1, 3, 3, 2, 1, 3, 3, 2, 3, 3, 3, 2, 2, 1, 2, 1, 3, 2,
       2, 2, 3, 1, 1, 1, 1, 2, 1, 1, 3, 1, 2, 3, 2, 1, 2, 2, 1, 3, 3, 3,
       2, 3, 3, 1, 1, 1, 2, 3, 3, 1, 2, 2, 2, 3, 3, 3, 3, 2, 2, 1, 1, 3,
       3, 3, 3, 2, 3, 3, 2, 3, 1, 1])

## Classification Report

In [ ]:
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        39
           2       0.93      1.00      0.96        37
           3       1.00      0.93      0.96        44

    accuracy                           0.97       120
   macro avg       0.97      0.98      0.98       120
weighted avg       0.98      0.97      0.98       120

## Applying the Model to make Prediction on a real Data ( By User )

In [ ]:
def pred_model():
  print("You have chosen the 'Know Your Iris Type' Option!")
  try:
    sepal_len = float(input("Enter your Sepal Lenght: "))
    sepal_wid = float(input("Enter your Sepal Width: "))
    petal_len = float(input("Enter your Petal Lenght: "))
    petal_wid = float(input("Enter your Petal Width: "))

    # Create a DataFrame from the user input
    user_input = pd.DataFrame([[sepal_len, sepal_wid, petal_len, petal_wid]],
                              columns=['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width'])

    # Predict using the trained SVM model
    prediction = svm.predict(user_input)

    # Create a reverse map for species names
    reverse_species_map = {v: k for k, v in species_map.items()}
    predicted_species = reverse_species_map[prediction[0]]

    print(f"\nBased on the input, the Iris type is: {predicted_species}")
  except ValueError:
    print("Invalid input. Please enter numerical values for measurements.")
  except KeyError:
    print("Prediction out of expected range. The model might need more diverse training data.")

In [ ]:
while True:
  print("\n--- Iris Classification System ---\n")
  print("1. Know your Iris type")
  print("2. Exit")

  choice = input("Enter your choice (1 or 2): ")

  if choice == '1':
    pred_model()
  elif choice == '2':
    print("Exiting Iris Classification System. Goodbye!")
    break
  else:
    print("Invalid choice. Please enter 1 or 2.")

--- Iris Classification System ---

1. Know your Iris type
2. Exit
Enter your choice (1 or 2): 5.1
Invalid choice. Please enter 1 or 2.

--- Iris Classification System ---

1. Know your Iris type
2. Exit
Enter your choice (1 or 2): 3.5
Invalid choice. Please enter 1 or 2.

--- Iris Classification System ---

1. Know your Iris type
2. Exit
Enter your choice (1 or 2): 1
You have chosen the 'Know Your Iris Type' Option!
Enter your Sepal Lenght: 5.1
Enter your Sepal Width: 3.5
Enter your Petal Lenght: 1.4
Enter your Petal Width: 0.2

Based on the input, the Iris type is: setosa

--- Iris Classification System ---

1. Know your Iris type
2. Exit
Enter your choice (1 or 2): 2
Exiting Iris Classification System. Goodbye!